
pipeline {
    agent any

    stages {

       stage('Initialize') {
            steps {
                echo 'Initial : Delete all containers and images'
                sh 'docker stop $(docker ps -a -q)'
                sh 'docker rm $(docker ps -a -q)'
                sh 'docker rmi $(docker images -q)'

                def currentPath = sh(returnStdout: true, script: 'pwd').trim()
                echo "Current path is ${currentPath}"
            }
        }

        stage('build stage') {
            steps {
                script {
                     sh 'docker build -t my-image ./Lab_Jenkins'
                     sh  'docker run -d -p 8085:3000 my-image'
                }
            }

        }
        
    }
}
