pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                sh    "ls "
                sh    " docker --version "
                sh    " sudo docker ps -a "
            }
        }
    }
}
