

pipeline {
    agent any

    stages {
        stage('Print Current Path') {
            steps {
                script {
                    def currentPath = sh(returnStdout: true, script: 'pwd').trim()
                    echo "Current path is ${currentPath}"

        
                     sh 'docker build -t my-image ./Lab_Jenkins'
                     sh  'docker run -d -p 8085:3000 my-image'
                }
            }

        }

        
    }
}
