pipeline {
    agent any

    environment {
        DOCKER_CONTAINER_NAME = "lab_docker_jenkins-container"
        DOCKER_IMAGE_NAME     = "lab_docker_jenkins-image"
    }

    stages {
        stage('Initialize') {
            steps {
                echo 'Initial : Delete  containers and images'
                # remove all containers
                sh "docker rm -f $(docker ps -a -q)"
                # remove all images
                sh "docker rmi -f $(docker images -q)"
                
                // sh "docker stop ${DOCKER_CONTAINER_NAME}"
                // sh "docker rm ${DOCKER_CONTAINER_NAME}"
                // sh "docker rmi ${DOCKER_IMAGE_NAME}"
            }
        }

        stage('Build Stage') {
            steps {
                dir('Lab_docker_Jenkins') { // change directory to Lab_docker_Jenkins
                    echo "Current path is ${pwd()}"
                    sh "docker build -t ${DOCKER_IMAGE_NAME} ."
                }
            }
        }

        stage('Run Stage') {
            steps {
                sh "docker run -d -p 8085:3000 --name ${DOCKER_CONTAINER_NAME} ${DOCKER_IMAGE_NAME}"
            }
        }

    
       

    }
}
