pipeline {
    agent any

    stages {

       stage('Initialize') {
            steps {
                echo 'Initial : Delete  containers and images'
                sh 'docker stop LAB_docker_jenkins-container || true'
                sh 'docker rm LAB_docker_jenkins-container || true'
                sh 'docker rmi LAB_docker_jenkins-image || true'
            }
        }

        stage('Build Stage') {
            steps {
                dir('Lab_docker_Jenkins') {
                    echo "Current path is ${pwd()}"
                    sh 'docker build -t LAB_docker_jenkins-image .'
                }
            }
        }

        stage('run test') {
            steps {
                sh 'docker run -d -p 8085:3000 --name LAB_docker_jenkins-container LAB_docker_jenkins-image'
            }
        }

    }
}
